# Generated by Django 4.1.2 on 2022-11-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_compeleted', models.BooleanField(default=False)),
                ('due_time', models.DateTimeField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'green'), ('medium', 'yellow'), ('high', 'red')], default='medium', max_length=6)),
            ],
        ),
    ]
